apiVersion: v1
kind: Service
metadata:
  name: memory-drive-frontend
  namespace: memory-drive
  labels:
    app.kubernetes.io/name: memory-drive
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: memory-drive
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
