name: Docker Image CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

env:
  AWS_REGION: eu-north-1
  BACKEND_REPOSITORY: learning/memory-drive-k8s-application 
  FRONTEND_REPOSITORY: learning/memory-drive-frontend
jobs:

  build:

    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION}}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    

    - name: Build the Backend Docker image
      run: |
        docker build \
          -f Dockerfile.backend \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPOSITORY }}:${{ github.sha }} \
          .
    
    - name: Push the Backend Docker image
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPOSITORY }}:${{ github.sha }}


    - name: Build the Frontend Docker image
      run: |
        docker build \
          -f Dockerfile.frontend \
          -t ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPOSITORY }}:${{ github.sha }} \
          .
    
    - name: Push the Frontend Docker image
      run: |
        docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPOSITORY }}:${{ github.sha }}
      
    - name: Install yq
      run: |
        sudo wget -qO /usr/local/bin/yq \
          https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

        sudo chmod +x /usr/local/bin/yq

        yq --version

    - name: Update Backend Deployment
      run: |
        yq -i '
        .spec.template.spec.containers[0].image =
        "${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_REPOSITORY }}:${{ github.sha }}" 
        ' k8s/05-backend-deployment.yaml
        
    - name: Update Frontend Deployment
      run: |
        yq -i '
        .spec.template.spec.containers[0].image =
        "${{ steps.login-ecr.outputs.registry }}/${{ env.FRONTEND_REPOSITORY }}:${{ github.sha }}" 
        ' k8s/07-frontend-deployment.yaml
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit updated manifests
      run: |
        git add k8s/

        if git diff --cached --quiet; then
          echo "No manifest changes"
          exit 0
        fi

        git commit -m "Update image tags to ${{ github.sha }}"
        git push origin HEAD:main
